/**
 * File functions.js.
 *
 * Bootstrap classes added to select elements.
 *
 * Uses jQuery to add classes to elements which are auto-generated by Wordpress.
 */
jQuery(document).ready(function() {
  jQuery('table').addClass('table');
  jQuery('input[type=submit]').addClass('btn btn-default');
  jQuery('input[type=text], textarea').addClass('form-control');
  jQuery('.widget .panel ul').addClass('list-group');
  jQuery('.widget .panel ul li').addClass('list-group-item');
  jQuery('.widget.widget_search > div').removeClass('panel panel-default');
  jQuery('.comment article').addClass('media');
});
